import os
import csv
from faker import Faker
from datetime import datetime

# Function to generate and write fake data to a CSV file with a timestamp
def generate_and_write_fake_data(output_folder, num_rows):
    fake = Faker()

    # list of diseases IF YOU HAVE A BETTER WAY PLEASE SHARE THIS WITH ME CAUSE I STILL CANT FIGURE OUT HOW TO MAKE PART EASIER
    diseases = [
        "Abdominal aortic aneurysm",
        "Acne",
        "Acute cholecystitis",
        "Acute lymphoblastic leukaemia",
        "Acute lymphoblastic leukaemia: Children",
        "Acute lymphoblastic leukaemia: Teenagers and young adults",
        "Acute myeloid leukaemia",
        "Acute myeloid leukaemia: Children",
        "Acute myeloid leukaemia: Teenagers and young adults",
        "Acute pancreatitis",
        "Adenomyosis",
        "Addison’s disease",
        "Alcohol-related liver disease",
        "Allergic rhinitis",
        "Allergies",
        "Alzheimer’s disease",
        "Anal cancer",
        "Anaphylaxis",
        "Angina",
        "Angioedema",
        "Ankylosing spondylitis",
        "Anorexia nervosa",
        "Anxiety",
        "Anxiety disorders in children",
        "Appendicitis",
        "Arterial thrombosis",
        "Arthritis",
        "Asbestosis",
        "Asthma",
        "Atopic eczema",
        "Atrial fibrillation",
        "Attention deficit hyperactivity disorder (ADHD)",
        "Autistic spectrum disorder (ASD)",
        "Bacterial vaginosis",
        "Benign prostate enlargement",
        "Bile duct cancer (cholangiocarcinoma)",
        "Binge eating",
        "Bipolar disorder",
        "Bladder cancer",
        "Blood poisoning (sepsis)",
        "Bone cancer",
        "Bone cancer: Teenagers and young adults",
        "Bowel cancer",
        "Bowel incontinence",
        "Bowel polyps",
        "Brain stem death",
        "Brain tumours",
        "Brain tumours: Children",
        "Brain tumours: Teenagers and young adults",
        "Breast cancer (female)",
        "Breast cancer (male)",
        "Bronchiectasis",
        "Bronchitis",
        "Bulimia",
        "Bunion",
        "Carcinoid syndrome and carcinoid tumours",
        "Catarrh",
        "Cellulitis",
        "Cerebral palsy",
        "Cervical cancer",
        "Chest infection",
        "Chest pain",
        "Chickenpox",
        "Chilblains",
        "Chlamydia",
        "Chronic fatigue syndrome",
        "Chronic kidney disease",
        "Chronic lymphocytic leukaemia",
        "Chronic myeloid leukaemia",
        "Chronic obstructive pulmonary disease",
        "Chronic pain",
        "Chronic pancreatitis",
        "Cirrhosis",
        "Clostridium difficile",
        "Coeliac disease",
        "Cold sore",
        "Coma",
        "Common cold",
        "Common heart conditions",
        "Congenital heart disease",
        "Conjunctivitis",
        "Constipation",
        "Coronavirus (COVID-19)",
        "Cough",
        "Crohn’s disease",
        "Croup",
        "Cystic fibrosis",
        "Cystitis",
        "Deafblindness",
        "Deep vein thrombosis",
        "Dehydration",
        "Dementia",
        "Dementia with Lewy bodies",
        "Dental abscess",
        "Depression",
        "Dermatitis herpetiformis",
        "Diabetes",
        "Diarrhoea",
        "Discoid eczema",
        "Diverticular disease and diverticulitis",
        "Dizziness (Lightheadedness)",
        "Down’s syndrome",
        "Dry mouth",
        "Dysphagia (swallowing problems)",
        "Dystonia",
        "Earache",
        "Earwax build-up",
        "Ebola virus disease",
        "Ectopic pregnancy",
        "Edwards’ syndrome",
        "Endometriosis",
        "Epilepsy",
        "Erectile dysfunction (impotence)",
        "Escherichia coli (E. coli) O157",
        "Ewing sarcoma",
        "Ewing sarcoma: Children",
        "Eye cancer",
        "Febrile seizures",
        "Feeling of something in your throat (Globus)",
        "Fever in adults",
        "Fever in children",
        "Fibroids",
        "Fibromyalgia",
        "Farting",
        "Flu",
        "Foetal alcohol syndrome",
        "Food poisoning",
        "Functional neurological disorder (FND)",
        "Fungal nail infection",
        "Gallbladder cancer",
        "Gallstones",
        "Ganglion cyst",
        "Gastroenteritis",
        "Gastro-oesophageal reflux disease (GORD)",
        "Genital herpes",
        "Genital symptoms",
        "Genital warts",
        "Germ cell tumours",
        "Glandular fever",
        "Gonorrhoea",
        "Gout",
        "Gum disease",
        "Haemorrhoids (piles)",
        "Hand, foot and mouth disease",
        "Hay fever",
        "Head and neck cancer",
        "Head lice and nits",
        "Headaches",
        "Hearing loss",
        "Heart attack",
        "Heart failure",
        "Hepatitis A",
        "Hepatitis B",
        "Hepatitis C",
        "Hiatus hernia",
        "High cholesterol",
        "HIV",
        "Hodgkin lymphoma",
        "Hodgkin lymphoma: Children",
        "Hodgkin lymphoma: Teenagers and young adults",
        "Huntington’s disease",
        "Hyperglycaemia (high blood sugar)",
        "Hyperhidrosis",
        "Hypoglycaemia (low blood sugar)",
        "Idiopathic pulmonary fibrosis",
        "Impetigo",
        "Indigestion",
        "Ingrown toenail",
        "Inherited heart conditions",
        "Insomnia",
        "Iron deficiency anaemia",
        "Irritable bowel syndrome (IBS)",
        "Itching",
        "Itchy bottom",
        "Kaposi’s sarcoma",
        "Kidney cancer",
        "Kidney infection",
        "Kidney stones",
        "Labyrinthitis",
        "Lactose intolerance",
        "Laryngeal (larynx) cancer",
        "Laryngitis",
        "Leg cramps",
        "Lichen planus",
        "Lipoedema",
        "Liver cancer",
        "Liver disease",
        "Liver tumours",
        "Loss of libido",
        "Lung cancer",
        "Lupus",
        "Lyme disease",
        "Lymphoedema",
        "Lymphogranuloma venereum (LGV)",
        "Malaria",
        "Malignant brain tumour (cancerous)",
        "Malnutrition",
        "Measles",
        "Meningitis",
        "Menopause",
        "Mesothelioma",
        "Middle ear infection (otitis media)",
        "Migraine",
        "Miscarriage",
        "Motor neurone disease (MND)",
        "Mouth cancer",
        "Mouth ulcer",
        "Multiple myeloma",
        "Multiple sclerosis (MS)",
        "Mumps",
        "Meniere’s disease",
        "Myasthenia gravis",
        "Nasal and sinus cancer",
        "Nasopharyngeal cancer",
        "Neuroblastoma: Children",
        "Neuroendocrine tumours",
        "Non-alcoholic fatty liver disease (NAFLD)",
        "Non-Hodgkin lymphoma",
        "Non-Hodgkin lymphoma: Children",
        "Norovirus",
        "Nosebleed",
        "Obesity",
        "Obsessive compulsive disorder (OCD)",
        "Obstructive sleep apnoea",
        "Oesophageal cancer",
        "Oral thrush in adults",
        "Osteoporosis",
        "Osteosarcoma",
        "Otitis externa",
        "Ovarian cancer",
        "Ovarian cancer: Teenagers and young adults",
        "Ovarian cyst",
        "Overactive thyroid",
        "Paget’s disease of the nipple",
        "Pancreatic cancer",
        "Panic disorder",
        "Parkinson’s disease",
        "Patau’s syndrome",
        "Pelvic inflammatory disease",
        "Pelvic organ prolapse",
        "Penile cancer",
        "Peripheral neuropathy",
        "Personality disorder",
        "Pleurisy",
        "Pneumonia",
        "Polycystic ovary syndrome (PCOS)",
        "Polymyalgia rheumatica",
        "Post-polio syndrome",
        "Post-traumatic stress disorder (PTSD)",
        "Postnatal depression",
        "Pregnancy and baby",
        "Pressure ulcers",
        "Prostate cancer",
        "Psoriasis",
        "Psoriatic arthritis",
        "Psychosis",
        "Pubic lice",
        "Rare tumours",
        "Raynaud’s phenomenon",
        "Reactive arthritis",
        "Restless legs syndrome",
        "Retinoblastoma: Children",
        "Rhabdomyosarcoma",
        "Rheumatoid arthritis",
        "Ringworm and other fungal infections",
        "Rosacea",
        "Scabies",
        "Scarlet fever",
        "Schizophrenia",
        "Scoliosis",
        "Septic shock",
        "Shingles",
        "Shortness of breath",
        "Sickle cell disease",
        "Sinusitis",
        "Sjogren’s syndrome",
        "Skin cancer (melanoma)",
        "Skin cancer (non-melanoma)",
        "Skin rashes in children",
        "Slapped cheek syndrome",
        "Soft tissue sarcomas",
        "Soft tissue sarcomas: Teenagers and young adults",
        "Sore throat",
        "Spleen problems and spleen removal",
        "Stillbirth",
        "Stomach ache and abdominal pain",
        "Stomach cancer",
        "Stomach ulcer",
        "Streptococcus A (strep A)",
        "Stress, anxiety and low mood",
        "Sudden infant death syndrome (SIDS)",
        "Suicide",
        "Sunburn",
        "Supraventricular tachycardia",
        "Swollen glands",
        "Syphilis",
        "Testicular cancer",
        "Testicular cancer: Teenagers and young adults",
        "Testicular lumps and swellings",
        "Thirst",
        "Threadworms",
        "Thrush",
        "Thyroid cancer",
        "Thyroid cancer: Teenagers and young adults",
        "Tinnitus",
        "Tonsillitis",
        "Tooth decay",
        "Toothache",
        "Transient ischaemic attack (TIA)",
        "Trigeminal neuralgia",
        "Tuberculosis (TB)",
        "Type 1 diabetes",
        "Type 2 diabetes",
        "Trichomonas infection",
        "Transverse myelitis",
        "Ulcerative colitis",
        "Underactive thyroid",
        "Urinary incontinence",
        "Urinary tract infection (UTI)",
        "Urinary tract infection (UTI) in children",
        "Urticaria (hives)",
        "Vaginal cancer",
        "Vaginal discharge",
        "Varicose eczema",
        "Venous leg ulcer",
        "Vertigo",
        "Vitamin B12 or folate deficiency anaemia",
        "Vomiting in adults",
        "Vulval cancer",
        "Warts and verrucas",
        "Whooping cough",
        "Wilms’ tumour",
        "Womb (uterus) cancer",
        "Yellow fever"

        # Add more diseases as needed
    ]
    blood_types = [
        "A+",
        "A-",
        "B+",
        "B-",
        "AB+",
        "AB-",
        "O+",
        "O-",
    ]

    # Specify the fieldnames for the CSV, rewrite the names to match your primary/f-keys, filenames impact your csv cell row A so this makes it easier to export into a db.
    fieldnames = [
        "Name",
        "Data of Birth",
        "Building Number",
        "Street Address",
        "Street Name",
        "Street Suffix",
        "City",
        "Postcode",
        "Country",
        "Country Code",
        "Timezone",
        "Job",
        "Company",
        "Company Email",
        "Social Security Number",
        "Currency",
        "Bank",
        "Bank IBAN",
        "Bank SWIFT-Branch/Office",
        "Bank SWIFT-11 digit",
        "Credit Card Provider",
        "Credit Card Number",
        "CC Security Code",
        "CC Expire",
        "CC Full",
        "IPv4 Public",
        "IPv4 Private",
        "MAC Address",
        "MRN",
        "Disease",  # Add the Disease field
        "Blood Type",
        "Gender",
    ]

    # Get the current timestamp
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")

    # Define the CSV filename with the timestamp
    csv_filename = os.path.join(output_folder, f"fake_data_{timestamp}.csv")

    with open(csv_filename, mode="w", newline="", encoding="utf-8") as csv_file:  # Specify UTF-8 encoding
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

        # Write the header row
        writer.writeheader()

        # Generate and write fake data for the specified number of rows
        for _ in range(num_rows):
            mrn_letter = fake.random_uppercase_letter() * fake.random_element(
                [2, 3])  # Generate 2 or 3 random uppercase letters
            mrn_numbers = fake.random_number(digits=10 - len(mrn_letter))  # Generate the remaining numbers
            mrn = mrn_letter + str(mrn_numbers)

            # Randomly select a disease or mark the person as healthy (None)
            disease = fake.random_element(diseases + [None])

            # Randomly select a blood type
            blood_type = fake.random_element(blood_types)

            # Randomly select a gender
            gender = fake.random_element(["Male", "Female"])

            fake_data = {
                "Name": fake.name(),
                "Data of Birth": (fake.date_between(start_date='-60y', end_date='-20y')),
                "Building Number": fake.building_number(),
                "Street Address": fake.street_address(),
                "Street Name": fake.street_name(),
                "Street Suffix": fake.street_suffix(),
                "City": fake.city(),
                "Postcode": fake.postcode(),
                "Country": fake.country(),
                "Country Code": fake.date_time_this_decade(),
                "Timezone": fake.country_code(),
                "Job": fake.job(),
                "Company": fake.company(),
                "Company Email": fake.company_email(),
                "Social Security Number": fake.ssn(),
                "Currency": fake.currency(),
                "Bank": fake.bank_country(),
                "Bank IBAN": fake.iban(),
                "Bank SWIFT-Branch/Office": fake.swift(length=8, use_dataset=True),
                "Bank SWIFT-11 digit": fake.swift(length=11, use_dataset=True),
                "Credit Card Provider": fake.credit_card_provider(),
                "Credit Card Number": fake.credit_card_number(card_type="discover"),
                "CC Security Code": fake.credit_card_security_code(card_type="discover"),
                "CC Expire": fake.credit_card_expire(),
                "CC Full": fake.credit_card_full(card_type="discover"),
                "IPv4 Public": fake.ipv4_public(),
                "IPv4 Private": fake.ipv4_private(),
                "MAC Address": (fake.hexify(text="MAC:: ^^:^^:^^:^^:^^:^^:^^", upper=True)),
                "MRN": mrn,
                "Disease": disease,  # Add the disease to the data
                "Blood Type": blood_type,
            }

            # Write the data row
            writer.writerow(fake_data)

    print(f"Fake data written to {csv_filename}")

# Specify the output folder and the number of rows you want in the CSV
output_folder = os.path.expanduser(r"C:\Users\sidpa\Desktop\outputs")  # Use a raw string (r) or escape backslashes
num_rows = 10  # Change this to the desired number of rows

# Generate and write fake data to the CSV with a timestamp
generate_and_write_fake_data(output_folder, num_rows)
